import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, Copy, CreditCard, ExternalLink, LoaderCircle, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { useParams } from "react-router-dom";
import api from "../api/api";

export default function PublicBooking() {
  const { username } = useParams();
  const [data, setData] = useState(null); const [error, setError] = useState("");
  const [step, setStep] = useState(1); const [service, setService] = useState(null);
  const [date, setDate] = useState(""); const [slots, setSlots] = useState([]); const [slot, setSlot] = useState(null); const [loadingSlots, setLoadingSlots] = useState(false);
  const [customer, setCustomer] = useState({ customer_name:"",customer_email:"",customer_phone:"" });
  const [checkout, setCheckout] = useState(null); const [payment, setPayment] = useState({payment_method:"upi",payment_reference:"",screenshot:""}); const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{api.get(`/booking/public/${encodeURIComponent(username)}`).then(({data})=>setData(data)).catch((e)=>setError(e.response?.data?.error||"Booking page unavailable."));},[username]);
  useEffect(()=>{if(!service||!date)return;setLoadingSlots(true);api.get(`/booking/public/${encodeURIComponent(username)}/slots`,{params:{service_id:service.id,date}}).then(({data})=>setSlots(data.slots||[])).catch((e)=>setError(e.response?.data?.error||"Unable to load slots.")).finally(()=>setLoadingSlots(false));},[service,date,username]);
  useEffect(()=>{if(checkout?.payment_settings?.upi_enabled)setPayment((p)=>({...p,payment_method:"upi"}));else if(checkout?.payment_settings?.razorpay_enabled)setPayment((p)=>({...p,payment_method:"razorpay"}));},[checkout]);
  const minDate=useMemo(()=>new Date().toISOString().slice(0,10),[]);
  const createBooking=async(event)=>{event.preventDefault();try{setSubmitting(true);const {data:created}=await api.post(`/booking/public/${encodeURIComponent(username)}/book`,{service_id:service.id,starts_at:slot.starts_at,...customer});setCheckout(created);setStep(created.booking.amount_paise>0?4:5);}catch(e){setError(e.response?.data?.error||"Unable to reserve this slot.");}finally{setSubmitting(false)}};
  const upload=(event)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")||file.size>3*1024*1024)return setError("Choose an image under 3 MB.");const r=new FileReader();r.onload=()=>setPayment((p)=>({...p,screenshot:r.result}));r.readAsDataURL(file)};
  const submitPayment=async(event)=>{event.preventDefault();try{setSubmitting(true);const {data:result}=await api.post(`/booking/public/booking/${checkout.lookup_token}/payment`,payment);setCheckout((c)=>({...c,result}));setStep(5);}catch(e){setError(e.response?.data?.error||"Unable to submit payment details.");}finally{setSubmitting(false)}};
  if(!data&&!error)return <PageShell><LoaderCircle className="h-9 w-9 animate-spin text-white"/></PageShell>;
  if(error&&!data)return <PageShell><div className="rounded-lg bg-white p-8 text-center"><h1 className="text-2xl font-bold">Booking unavailable</h1><p className="mt-2 text-slate-500">{error}</p></div></PageShell>;
  const {profile,services}=data;
  return <div className="min-h-screen bg-gradient-to-br from-cyan-500 via-blue-600 to-violet-700 px-4 py-8 sm:py-12"><main className="mx-auto w-full max-w-3xl overflow-hidden rounded-lg bg-white shadow-2xl">
    <header className="bg-slate-950 px-6 py-8 text-center text-white sm:px-10"><div className="mx-auto flex h-20 w-20 items-center justify-center overflow-hidden rounded-full border-4 border-white/70 bg-white/10 text-2xl font-bold">{profile.profile_picture_url?<img src={profile.profile_picture_url} alt="" className="h-full w-full object-cover"/>:(profile.display_name||profile.username).slice(0,1).toUpperCase()}</div><h1 className="mt-4 text-2xl font-bold">{profile.display_name||profile.username}</h1>{profile.professional_title&&<p className="mt-1 text-sm text-cyan-200">{profile.professional_title}</p>}{profile.bio&&<p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-300">{profile.bio}</p>}</header>
    <div className="border-b border-slate-100 px-5 py-4"><div className="mx-auto flex max-w-xl items-center justify-between text-xs font-bold text-slate-400">{["Service","Time","Details","Payment"].map((label,index)=><span key={label} className={step>=index+1?"text-brand-700":""}>{index+1}. {label}</span>)}</div></div>
    <section className="p-5 sm:p-8">{error&&<div className="mb-5 rounded-lg bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}<button onClick={()=>setError("")} className="float-right">×</button></div>}
      {step===1&&<div><Title icon={CalendarDays} title="Choose a service" subtitle="Select the appointment that works for you."/><div className="mt-6 grid gap-3 sm:grid-cols-2">{services.map((item)=><button key={item.id} onClick={()=>{setService(item);setStep(2)}} className="rounded-lg border border-slate-200 p-5 text-left transition hover:-translate-y-0.5 hover:border-brand-400 hover:shadow-lg"><div className="flex items-start justify-between gap-3"><h2 className="font-bold text-slate-950">{item.name}</h2><span className="font-bold text-brand-700">{item.price_paise?`₹${item.price_paise/100}`:"Free"}</span></div><p className="mt-2 text-sm leading-5 text-slate-500">{item.description}</p><p className="mt-4 flex items-center gap-3 text-xs font-semibold text-slate-500"><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{item.duration_minutes} min</span><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{item.appointment_type}</span></p></button>)}</div></div>}
      {step===2&&<div><Back onClick={()=>setStep(1)}/><Title icon={Clock3} title="Choose date and time" subtitle={`Times shown in ${profile.timezone}.`}/><input type="date" min={minDate} value={date} onChange={(e)=>{setDate(e.target.value);setSlot(null)}} className="input mt-6"/>{loadingSlots?<LoaderCircle className="mx-auto mt-8 h-7 w-7 animate-spin text-brand-600"/>:<div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map((item)=><button key={item.starts_at} onClick={()=>setSlot(item)} className={`rounded-lg border px-3 py-3 text-sm font-bold ${slot?.starts_at===item.starts_at?"border-brand-600 bg-brand-600 text-white":"border-slate-200 hover:border-brand-300"}`}>{item.label}</button>)}{date&&!slots.length&&<p className="col-span-full py-8 text-center text-sm text-slate-500">No slots available on this date.</p>}</div>}<button disabled={!slot} onClick={()=>setStep(3)} className="btn-primary mt-6 w-full justify-center">Continue</button></div>}
      {step===3&&<form onSubmit={createBooking}><Back onClick={()=>setStep(2)}/><Title icon={UserRound} title="Your details" subtitle="We’ll use these details only for this appointment."/><div className="mt-6 space-y-4"><Field label="Full name" value={customer.customer_name} onChange={(v)=>setCustomer({...customer,customer_name:v})} required/><Field label="Email" type="email" value={customer.customer_email} onChange={(v)=>setCustomer({...customer,customer_email:v})} required/><Field label="Phone number (optional)" value={customer.customer_phone} onChange={(v)=>setCustomer({...customer,customer_phone:v})}/><label className="flex items-start gap-2 text-xs leading-5 text-slate-500"><input type="checkbox" required className="mt-1"/>I agree that my details will be shared with this creator to manage the appointment.</label></div><button disabled={submitting} className="btn-primary mt-6 w-full justify-center">{submitting?"Reserving...":service.price_paise?"Reserve and continue to payment":"Request appointment"}</button></form>}
      {step===4&&checkout&&<form onSubmit={submitPayment}><Title icon={CreditCard} title="Pay the creator directly" subtitle={`Amount due: ₹${checkout.booking.amount_paise/100}`}/><div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">Payment goes directly to the creator. JustDMs does not collect, hold, verify, or deduct commission from this payment.</div><div className="mt-5 space-y-4">{checkout.payment_settings?.upi_enabled&&<label className="block rounded-lg border border-slate-200 p-4"><input type="radio" name="method" checked={payment.payment_method==="upi"} onChange={()=>setPayment({...payment,payment_method:"upi"})}/> <strong>UPI</strong><p className="mt-2 text-sm text-slate-600">Pay to {checkout.payment_settings.upi_display_name||"Creator"}: <strong>{checkout.payment_settings.upi_id}</strong></p>{checkout.payment_settings.upi_qr_path&&<img src={checkout.payment_settings.upi_qr_path} alt="UPI QR" className="mt-3 h-44 w-44 rounded-lg border object-contain"/>}<div className="mt-3 flex flex-wrap gap-2"><button type="button" className="btn-secondary" onClick={()=>navigator.clipboard.writeText(checkout.payment_settings.upi_id)}><Copy className="h-4 w-4"/>Copy UPI ID</button>{checkout.payment_settings.upi_url&&<a className="btn-primary" href={checkout.payment_settings.upi_url}>Open UPI app</a>}</div></label>}{checkout.payment_settings?.razorpay_enabled&&<label className="block rounded-lg border border-slate-200 p-4"><input type="radio" name="method" checked={payment.payment_method==="razorpay"} onChange={()=>setPayment({...payment,payment_method:"razorpay"})}/> <strong>Razorpay</strong><p className="mt-2 text-sm text-slate-500">This creator-owned payment page may use a static amount. Verify the amount before paying.</p><a href={checkout.payment_settings.razorpay_payment_link} target="_blank" rel="noreferrer" className="btn-primary mt-3"><ExternalLink className="h-4 w-4"/>Pay with Razorpay</a></label>}<Field label="Payment reference (optional)" value={payment.payment_reference} onChange={(v)=>setPayment({...payment,payment_reference:v})}/><label className="block"><Label>Payment screenshot (optional)</Label><input className="input" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label></div><p className="mt-4 text-xs leading-5 text-slate-500">Submitting a reference or screenshot does not verify payment. The creator must check their own account and confirm manually.</p><button disabled={submitting} className="btn-primary mt-5 w-full justify-center">{submitting?"Submitting...":"I have paid — submit for review"}</button></form>}
      {step===5&&checkout&&<div className="py-6 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-500"/><h2 className="mt-4 text-2xl font-bold">{checkout.booking.amount_paise?"Payment submitted for review":"Booking request received"}</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-slate-500">{checkout.result?.message||"The creator will review and confirm your appointment. You’ll receive an email when its status changes."}</p><div className="mx-auto mt-6 max-w-md rounded-lg bg-slate-50 p-4 text-left text-sm"><p><strong>Service:</strong> {service.name}</p><p className="mt-1"><strong>Time:</strong> {new Date(checkout.booking.starts_at).toLocaleString()}</p><p className="mt-1"><strong>Status:</strong> {checkout.result?.status||checkout.booking.status}</p></div></div>}
    </section><footer className="border-t border-slate-100 px-6 py-4 text-center text-xs text-slate-500"><ShieldCheck className="mr-1 inline h-4 w-4"/>Secure booking powered by <a href="https://justdms.in" className="font-bold text-brand-700">JustDMs</a></footer>
  </main></div>;
}

function PageShell({children}){return <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-cyan-500 via-blue-600 to-violet-700 p-5">{children}</div>}
function Title({icon:Icon,title,subtitle}){return <div><Icon className="h-6 w-6 text-brand-600"/><h2 className="mt-3 text-2xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>}
function Back({onClick}){return <button onClick={onClick} className="mb-5 inline-flex items-center gap-1 text-sm font-bold text-slate-500"><ArrowLeft className="h-4 w-4"/>Back</button>}
function Label({children}){return <span className="mb-2 block text-sm font-bold text-slate-700">{children}</span>}
function Field({label,value,onChange,type="text",...props}){return <label className="block"><Label>{label}</Label><input className="input" type={type} value={value} onChange={(e)=>onChange(e.target.value)} {...props}/></label>}
